version: "3.8"

services:
  mysqldb:
    container_name: "wallet_db"
    build:
      context: .
      target: build2
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    ports:
      - "3308:3306"
    volumes:
      -  dbdata:/var/lib/mysql
  api:
    container_name: "wallet_api"
    build:
      context: .
    ports:
      - "8070:8070"
    depends_on:
      - "mysqldb"
volumes:
  dbdata:
